### PR TITLE
Removed references to external entities, IP and companies. Fixed #14

### LINKED ISSUE #14: All references to specific hosts, domains and companies must be removed.
Hello,
the source code contains references to specific real hostnames, companies e-mail addresses and IP addresses (e.g. allowing TCP traffic in iptables firewall to existing third party server).
The code must be cleaned and all these information removed.

### PR DESCRIPTION
**Pull request by acataluddi**

### CODE REVIEW

**Comment by graphiclunarkid** [comment]
Thanks for sending this, @acataluddi - very useful!

I'd like to suggest a few improvements before we merge.

I think we should always comment out lines that won't parse unless they are changed (e.g where we've replaced a real IP address with `xxx.xxx.xxx.xxx`). At the moment this PR only does that in some places. We should also replace hard-coded values like email addresses with Ansible variables so users don't have to go hunting through the playbooks for them.

Places I spotted where we might need to comment out lines:
- https://github.com/equalitie/eqpress/pull/15/files#diff-a2e6723e6b5ed3334e6e7a34d025cd74R11
- https://github.com/equalitie/eqpress/pull/15/files#diff-a2e6723e6b5ed3334e6e7a34d025cd74R66

Values that I think should become Ansible variables:
- https://github.com/equalitie/eqpress/pull/15/files#diff-b1ffda63a8f21c15969f8caf61a82126R1
- https://github.com/equalitie/eqpress/pull/15/files#diff-9e9ea9c21b6a566496b55c66ba677465R13

I'm not sure providing a default `email_domain` is wise since it'll never be right now we've made the software generic.
- https://github.com/equalitie/eqpress/pull/15/files#diff-606b407a34fd6cfde84c2c1a3190044cR9

I suggest we remove this default and replace it with a mandatory Ansible variable set by the user.

If you'd like to make those changes and push them to this branch that'd be fantastic :smile: Let me know here if you have any questions or comments.

**Comment by acataluddi** [comment]
Hello Richard,
yes, I agree with the suggested modifications. I did them and updated the branch in this Pull Request.

Regards
Adriano C.

**Comment by graphiclunarkid** [comment]
Thanks for the update, @acataluddi! It turns out that `currentconnections.sh` isn't being used at the moment so I don't suppose it matters that it still contains a hardcoded email address. I think this is good to go :smile:

**Comment by acataluddi** [comment]
Thank you Richard for accepting it. 
About the hardcoded e-mail in `currentconnections.sh` (and others), for what is my understanding those e-mail addresses were just remarks: does Eqpress parse `.sh` remarks to build some automatic notification?

Regards
Adriano C.

**Comment by graphiclunarkid** [comment]
That seems unlikely - but I don't really know how this works for sure, sorry. @RamJett or @kheops2713 might be able to comment.

**Pull request merged**
